### ISSUE TITLE
Filter keys in spread object

### ISSUE THREAD

**Issue by mscienski** [sebmarkbage/ecmascript-rest-spread#16] opened 2016-07-13 23:50 UTC
The issue https://github.com/sebmarkbage/ecmascript-rest-spread/issues/3
had an example with lodash/omit. While complete computed properties were determined to be undesirable, perhaps the specific use case of filtering keys would be helpful.

`let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};`
`let y = {...x, !md5};`
`console.log(y); // {a: 1, b: 2, c: 3}`

This would allow us to golf blocks like

```
let y = {...x};
delete y.md5;
return y;
```

to 

```
return {...x, !md5};
```

**Comment by atticoos** [comment] 2016-07-14 01:18
Interesting idea, although this might get complicated in further cases.

For example, you can spread multiple objects, as well as nested objects

``` js
return {...x, ...y, !md5}
```

How would it know which object to filter against? Perhaps `!x.md5`.

I have come into scenarios where I want "all but these" properties too, but I personally questioned if that overextends the purpose behind spreading objects and feel like it may make more sense to use a reducer

**Comment by mscienski** [comment] 2016-07-14 01:22
I think with multiple objects, it would behave like multiple objects do now with duplicate keys, where ordering matters.

```
let x = {a: 1, b: 2};
let y = {...x, b:6};
console.log(y); // {a: 1, b: 6}
```

so this would become

```
let x = {a: 1, wibble: 'wobble'};
let y = {b: 2, wibble: 'baz'};
let z = {...x, !wibble, ...y};
let zzyx = {...x, ...y, !wibble}
console.log(z); // {a: 1, b: 2, wibble: 'baz'}
console.log(zzyx); // {a: 1, b: 2}
```

True, using something like `universalReduce` or `lodash/omit` could accomplish the same thing, but it would also be a nice language feature.

**Comment by nickzuber** [comment] 2016-07-15 15:55
@mscienski Do you think incorporating such a feature would start to creep out of scope of what the intended behavior of the spread operator? Sure this would be a cool feature to have, but do you think this feature belongs in the native behavior?

Also, what about a scenario like this

``` js
var c = true;

// ...

var obj = {a: true, b: true, c: true};

var newObj = {...obj, !c};
// newObj = {a: true, b: true, c: false}
// or
// newObj = {a: true, b: true}
```

How would we know which approach was intended?

**Comment by mscienski** [comment] 2016-07-15 16:08
Admittedly it's probably creeping on the scope of intended behavior of the spread operator. But it is such a common use case (at least in my experience), it's a high QOL improvement.

In your example, I'd say the latter case is the intended behavior, always. To minimize confusion, there could be a different syntax. `!` is the negation operator in JavaScript, so it was my first choice, but it could be any symbol that makes contextual sense.

E.g.
`let newObj = {...obj, ~c};`
`let newObj = {...obj, ^c};`

Even then, I'd argue that `{...obj, !c}` is still correct. With object shorthand notation in ES6, it's only ever a direct copy. Changing the value must be explicit.
E.g.

```
let x = true;
let obj = {x}; // {x: true}
let otherObj = {x: 2}; // {x: 2}
let otherOtherObj = {!x}; // syntax error
```

The spread operator would follow the same convention. Changing the value of a key must be explicit, the `!` would only be an omit operator when used with spread.

**Comment by sebmarkbage** [comment] 2016-07-18 02:21
Note that basic filter can be done in cooperation with the rest operator.

``` js
let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};
let { md5, ...y } = x;
```

It would be neat to have something like this or even more powerful filtering features but this is a bit of feature creep on this initial proposal. The initial proposal allows you to accomplish the basic tasks. Any additional complexity would need to warrant the additional syntax and use of more operators.

**Closed as completed by sebmarkbage** 2016-07-18 02:21 UTC

**Comment by simonbuchan** [comment] 2016-08-30 07:31
Being an expression does make it more flexible though I'm not too concerned..
_If_ this existed, I'd want the syntax `{ ...x, ...y, md5: delete }`, so long as it makes sense with the semantics (e.g. `x.get md5()` still runs)

**Comment by tomasdev** [comment] 2018-02-25 00:36
You can currently do this, instead of
```
let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};
let y = {...x, !md5};
console.log(y); // {a: 1, b: 2, c: 3}
```
do:
```
let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};
let {md5, ...y} = x;
console.log(y); // {a: 1, b: 2, c: 3}
```

Obviously the limit is the excluded properties must be known beforehand.

Now, this https://stackoverflow.com/questions/25553910/one-liner-to-take-some-properties-from-object-in-es-6 which is actually the opposite (create a new object, but only using `a,b,c` properties from source object) is somewhat something I'd like to be considered.
Like:
```
let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};
let { y: { a, b, c } } = x;
```
(currently, this saves `a`, `b` and `c` as variables, but not `y`)

**Comment by sfentress** [comment] 2018-04-13 19:24
One issue with using the solution

```
let x = {a: 1, b: 2, c: 3, md5: '83b0f2d70d7546ee634f801264c4a9b3'};
let {md5, ...y} = x;
console.log(y); // {a: 1, b: 2, c: 3}
```

is that many linters complain about unused variables. (E.g. the `no-unused-vars` rule in ESLint.) In the above example, we're creating the variable `md5` and doing nothing with it. And it might also cause confusions if we *do* want to use a variable named `md5` earlier or later in the scope.

**Comment by hax** [comment] 2018-04-26 12:49
@sfentress 
ESLint has a `ignoreRestSiblings` option (https://eslint.org/docs/rules/no-unused-vars#ignorerestsiblings). 
Another workaround: write `let {md5: _, ...y} = x`, and use `varsIgnorePattern` option to rule `_` out. Note, I still hope we can use some keyword (like `md5: delete`) or symbol (like `!md5`) in the future, because it will be more clear.

**Comment by nwpray** [comment] 2018-06-20 20:13
This is the specific scenario I ran into that would make this feature mega useful.

```
const user = {
    firstName: 'Bob',
    lastName: 'Jones',
    proxyFor: [
       { firstName: 'Sally' lastName: 'Jones' },
       { firstName: 'David', lastName: 'Jones' }
    ]
};

// (IDEAL) I would like to be able to aggregate the users something like this
const users = [ { ...user, currentUser: true, proxyFor: delete }, ...user.proxyFor ];

// (Current Solution A) Right now I'm stuck with something like this
const users = [ { ...user, currentUser: true }, ...user.ProxyFor ];
delete users[0].proxyFor;

// (Current Solution B) Or 
const { proxyFor, ...updatedUser } = user;
const users = [ { ...updatedUser, currentUser: true }, ...proxyFor ];

// (Probably other similar solutions) etc....
```
Both Solution A and Solution B can get pretty sticky in certain applications. Specifically, if you are trying to do the delete in a completely functional manner you end up having to break the chain with a whole new function block of some sort just to unpack or clean up after composition.

I understand that this could dive into a poor model design debate, but sometimes your not in control of the Objects contract.
